/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedJournalEntriesRouteImport } from './routes/_authenticated/journal-entries'
import { Route as AuthenticatedFundersRouteImport } from './routes/_authenticated/funders'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedExpenseCategoriesRouteImport } from './routes/_authenticated/expense-categories'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedFundersFunderIdRouteImport } from './routes/_authenticated/funders.$funderId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalEntriesRoute =
  AuthenticatedJournalEntriesRouteImport.update({
    id: '/journal-entries',
    path: '/journal-entries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFundersRoute = AuthenticatedFundersRouteImport.update({
  id: '/funders',
  path: '/funders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpenseCategoriesRoute =
  AuthenticatedExpenseCategoriesRouteImport.update({
    id: '/expense-categories',
    path: '/expense-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFundersFunderIdRoute =
  AuthenticatedFundersFunderIdRouteImport.update({
    id: '/$funderId',
    path: '/$funderId',
    getParentRoute: () => AuthenticatedFundersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expense-categories': typeof AuthenticatedExpenseCategoriesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/funders': typeof AuthenticatedFundersRouteWithChildren
  '/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expense-categories': typeof AuthenticatedExpenseCategoriesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/funders': typeof AuthenticatedFundersRouteWithChildren
  '/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expense-categories': typeof AuthenticatedExpenseCategoriesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/funders': typeof AuthenticatedFundersRouteWithChildren
  '/_authenticated/journal-entries': typeof AuthenticatedJournalEntriesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/dashboard'
    | '/expense-categories'
    | '/expenses'
    | '/funders'
    | '/journal-entries'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/funders/$funderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/dashboard'
    | '/expense-categories'
    | '/expenses'
    | '/funders'
    | '/journal-entries'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/funders/$funderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/expense-categories'
    | '/_authenticated/expenses'
    | '/_authenticated/funders'
    | '/_authenticated/journal-entries'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/funders/$funderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal-entries': {
      id: '/_authenticated/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof AuthenticatedJournalEntriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funders': {
      id: '/_authenticated/funders'
      path: '/funders'
      fullPath: '/funders'
      preLoaderRoute: typeof AuthenticatedFundersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expense-categories': {
      id: '/_authenticated/expense-categories'
      path: '/expense-categories'
      fullPath: '/expense-categories'
      preLoaderRoute: typeof AuthenticatedExpenseCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funders/$funderId': {
      id: '/_authenticated/funders/$funderId'
      path: '/$funderId'
      fullPath: '/funders/$funderId'
      preLoaderRoute: typeof AuthenticatedFundersFunderIdRouteImport
      parentRoute: typeof AuthenticatedFundersRoute
    }
  }
}

interface AuthenticatedFundersRouteChildren {
  AuthenticatedFundersFunderIdRoute: typeof AuthenticatedFundersFunderIdRoute
}

const AuthenticatedFundersRouteChildren: AuthenticatedFundersRouteChildren = {
  AuthenticatedFundersFunderIdRoute: AuthenticatedFundersFunderIdRoute,
}

const AuthenticatedFundersRouteWithChildren =
  AuthenticatedFundersRoute._addFileChildren(AuthenticatedFundersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpenseCategoriesRoute: typeof AuthenticatedExpenseCategoriesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFundersRoute: typeof AuthenticatedFundersRouteWithChildren
  AuthenticatedJournalEntriesRoute: typeof AuthenticatedJournalEntriesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpenseCategoriesRoute: AuthenticatedExpenseCategoriesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFundersRoute: AuthenticatedFundersRouteWithChildren,
  AuthenticatedJournalEntriesRoute: AuthenticatedJournalEntriesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
